import { test,expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import AxeBuilder from '@axe-core/playwright';
import { healthPanelsFixture } from './atlas-health-panels-fixture';
import { routeBrowserFixture } from './atlas-browser-fixture.mjs';

for(const viewport of [{width:390,height:950},{width:1280,height:720},{width:1280,height:950}])test(`One Health analytical panels ${viewport.width}×${viewport.height}`,async({page})=>{
 const bundle=healthPanelsFixture();
 await routeBrowserFixture(page,bundle,JSON.parse(readFileSync('.cache/atlas-fixture/map.json','utf8')));
 await page.setViewportSize(viewport);await page.emulateMedia({reducedMotion:'reduce',colorScheme:viewport.width===390?'dark':'light'});
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/atlas/');
 if(viewport.width===1280){await page.getByRole('button',{name:'Click to enter full screen'}).focus();await page.keyboard.press('Enter');}
 await page.getByRole('tab',{name:'One Health',exact:true}).click();
 const view=page.getByRole('region',{name:'One Health evidence'});
 const choose=async(name:string)=>{await view.locator('summary[aria-label="One Health view"]').click();await view.getByRole('option',{name,exact:true}).click();};
 await choose('Timeline');
 await expect(view.getByRole('heading',{name:'Aligned evidence timeline'})).toHaveClass('sr-only');
 await expect(view.locator('.atlas-oh-time-point')).toHaveCount(3);
 await expect(view.getByRole('heading',{name:'Undated or incomplete dates 3'})).toBeVisible();
 await expect(view.getByRole('heading',{name:'Reporting cutoffs 1'})).toBeVisible();
 await expect(view.getByRole('button',{name:/detection · 2022 · end unknown/})).toBeVisible();
 const unresolved=view.getByRole('button',{name:/unknown · Jul 2026/});
 await unresolved.click();
 await expect(view.getByRole('complementary')).toContainText('Jul 2026');
 await expect(view.getByRole('complementary')).toContainText('Date kindunknown');
 const month=view.getByRole('button',{name:/Synthetic sampled population\. sample collection\. Jul 2026/});
 await month.focus();await month.press('Enter');
 await expect(view.getByRole('complementary')).toContainText('Jul 2026');
 await expect(view.getByRole('complementary')).toContainText('Precisionmonth');
 await page.keyboard.press('Escape');
 expect((await new AxeBuilder({page}).include('.atlas-one-health').analyze()).violations).toEqual([]);
 await page.screenshot({path:`/tmp/atlas-panel-timeline-${viewport.width}-${viewport.height}.png`});
 await choose('Sampling');
 const sampling=view.getByRole('table',{name:'Reviewed sampling and positivity'});
 await expect(sampling).toContainText('0%');await expect(sampling).toContainText('Counts only');
 await sampling.getByRole('button',{name:'Counts only',exact:true}).click();
 await expect(view.getByRole('complementary')).toContainText('Sample pairing has not been established');
 await expect(view.getByRole('complementary')).toContainText('Poolingnot reported');
 expect((await new AxeBuilder({page}).include('.atlas-one-health').analyze()).violations).toEqual([]);
 await page.screenshot({path:`/tmp/atlas-panel-sampling-${viewport.width}-${viewport.height}.png`});
 await choose('Environment');
 await expect(view.locator('.atlas-oh-time-point')).toHaveCount(1);
 await expect(view.getByRole('complementary')).toContainText('Reported intervention');
 await expect(view).toContainText('Alignment does not establish an effect');
 await expect(view.getByRole('button',{name:/Synthetic condition with unresolved date kind.*Jul 2026/})).toBeVisible();
 await view.locator('summary[aria-label="One Health report"]').click();
 await view.getByRole('option').last().click();
 await expect(view.getByRole('complementary')).toContainText('Synthetic independent context');
 await expect(view.getByRole('complementary')).toContainText('no linked observation is asserted');
 expect((await new AxeBuilder({page}).include('.atlas-one-health').analyze()).violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(viewport.width===1280)expect(await page.locator('.atlas-workspace-scroll').evaluate(el=>el.scrollHeight<=el.clientHeight+1)).toBe(true);
 await page.screenshot({path:`/tmp/atlas-panel-environment-${viewport.width}-${viewport.height}.png`});
 expect(errors).toEqual([]);
});
