import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { monthsBefore } from "../src/lib/atlas";
import type { AtlasSiteBundle } from "../src/lib/atlas-vendor/1.5/site-types";

for (const width of [1440, 390]) test(`Reporting place and disease filters at ${width}px`, async ({ page }) => {
  test.skip(!process.env.ATLAS_REPORTING_BUNDLE, "Requires a reviewed reporting bundle");
  const bundle: AtlasSiteBundle = JSON.parse(readFileSync(process.env.ATLAS_REPORTING_BUNDLE!, "utf8"));
  const lassa = bundle.diseases.find(d => d.label === "Lassa fever")!;
  const countries = new Set(bundle.location_memberships.filter(m => m.area_code === "NG" && m.role !== "context").map(m => m.record_id));
  const diseases = new Set(bundle.disease_reviews.filter(r => r.disease_ids.includes(lassa.id)).map(r => r.record_id));
  const selected = bundle.records.filter(r => countries.has(r.id) && diseases.has(r.id));
  const documents = new Set(selected.map(r => r.document_id));
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width, height: 820 });
  await page.emulateMedia({ colorScheme: width === 390 ? "dark" : "light", reducedMotion: "reduce" });
  await page.goto(process.env.ATLAS_REPORTING_TEST_PATH ?? "/atlas/");
  const place = page.locator('summary[aria-label="Reporting place"]');
  const disease = page.locator('summary[aria-label="Reporting disease"]');
  const controls = page.locator(".atlas-filters");
  await expect(place).toBeVisible({ timeout: 120000 });
  await expect(disease.locator('svg[data-icon="virus"]')).toBeVisible();
  await place.click();
  await page.getByRole("searchbox", { name: "Search reporting place" }).fill("Nigeria");
  await page.getByRole("checkbox", { name: "Nigeria", exact: true }).check();
  await page.keyboard.press("Escape");
  await disease.click();
  await page.getByRole("searchbox", { name: "Search reporting disease" }).fill("Lassa");
  const choice = page.locator(".atlas-select-check").filter({ has: page.getByRole("checkbox", { name: "Lassa fever", exact: true }) });
  await expect(choice.locator(".atlas-select-count")).toHaveText(String(selected.length));
  await choice.getByRole("checkbox").check();
  await page.keyboard.press("Escape");
  const tabs = page.getByRole("tablist", { name: "Evidence views" });
  await expect(tabs.getByRole("tab", { name: "Reports", exact: true }).locator("b")).toHaveText(String(documents.size));
  const end = (await page.locator(".atlas-range-dates time").last().getAttribute("datetime"))!;
  await page.getByRole("button", { name: "3 months", exact: true }).click();
  const recent = selected.filter(record => record.publication.slice(0, 10) >= monthsBefore(end, 3));
  await expect(tabs.getByRole("tab", { name: "Reports", exact: true }).locator("b")).toHaveText(String(new Set(recent.map(record => record.document_id)).size));
  await page.getByRole("button", { name: "All dates", exact: true }).click();
  const source = page.locator('summary[aria-label="Reporting source"]');
  await source.click();
  await page.getByRole("checkbox", { name: "NCDC", exact: true }).check();
  await page.keyboard.press("Escape");
  await expect(tabs.getByRole("tab", { name: "Reports", exact: true }).locator("b")).toHaveText(String(new Set(selected.filter(record => record.channel_id === "ncdc").map(record => record.document_id)).size));
  await source.click();
  await page.getByRole("checkbox", { name: "All sources", exact: true }).check();
  await page.keyboard.press("Escape");
  for (const name of ["Reports", "One Health", "Analysis", "Trends"]) {
    await tabs.getByRole("tab", { name, exact: true }).click();
    await expect(place).toHaveText("Nigeria");
    await expect(disease).toHaveText("Lassa fever");
  }
  await page.locator(".atlas-controls").scrollIntoViewIfNeeded();
  await page.locator(".atlas-controls").screenshot({ path: `/tmp/atlas-filters-${width}.png` });
  const [p, d, s] = await Promise.all([place.boundingBox(), disease.boundingBox(), page.locator('summary[aria-label="Reporting source"]').boundingBox()]);
  expect(Math.abs(p!.y - d!.y)).toBeLessThan(2);
  expect(s!.y).toBeGreaterThan(p!.y);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  if (width === 1440) {
    await page.getByRole("button", { name: "Click to enter full screen" }).focus();
    await page.getByRole("button", { name: "Click to enter full screen" }).press("Enter");
    await expect(page.getByRole("dialog", { name: "ATLAS full screen" })).toBeVisible();
    await place.click();
    const box = (await page.getByRole("dialog", { name: "Reporting place", exact: true }).boundingBox())!;
    expect(box.y).toBeGreaterThanOrEqual(0);
    expect(box.y + box.height).toBeLessThanOrEqual((await place.boundingBox())!.y);
    await page.keyboard.press("Escape");
    await page.screenshot({ path: "/tmp/atlas-filters-fullscreen.png" });
  }
  await controls.locator('summary[aria-label^="Active rules"]').click();
  const advancedTopic = controls.locator('summary[aria-label="Reporting topic"]');
  await advancedTopic.click();
  await page.getByRole("searchbox", { name: "Search reporting topic" }).fill("Lassa");
  await page.keyboard.press("Escape");
  await expect(controls.locator(".atlas-rules")).toHaveAttribute("open", "");
  await page.getByRole("checkbox", { name: "Include background locations" }).check();
  await page.getByRole("button", { name: "Remove disease filter" }).click();
  await expect(disease).toHaveText("All diseases");
  await controls.locator('summary[aria-label^="Active rules"]').click();
  await controls.getByRole("button", { name: "Reset all", exact: true }).click();
  await expect(place).toHaveText("All places");
  await expect(tabs.getByRole("tab", { name: "Reports", exact: true }).locator("b")).toHaveText(String(new Set(bundle.records.map(r => r.document_id)).size));
  await place.click();
  await page.getByRole("searchbox", { name: "Search reporting place" }).fill("Location unspecified");
  await page.getByRole("checkbox", { name: "Location unspecified", exact: true }).check();
  await page.keyboard.press("Escape");
  await disease.click();
  await page.getByRole("searchbox", { name: "Search reporting disease" }).fill("Lassa");
  await page.getByRole("checkbox", { name: "Lassa fever", exact: true }).check();
  await page.keyboard.press("Escape");
  for (const name of ["One Health", "Analysis", "Reports", "Journeys"]) await tabs.getByRole("tab", { name, exact: true }).click();
  expect(errors).toEqual([]);
});

