import { selectAtlasOption } from './atlas-select-actions';
import { test, expect } from '@playwright/test';

for (const width of [390, 1466]) test(`English reports, paired quotations and briefing navigation at ${width}px`, async ({ page }) => {
  test.skip(!process.env.ATLAS_PRESENTATION_PREVIEW, 'Requires the matching producer presentation release');
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width, height: 832 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(process.env.ATLAS_PRESENTATION_PREVIEW!);
  await expect(page.getByRole('heading', { name: 'Reporting activity', exact: true })).toBeVisible();
  await expect(page.locator('.atlas-disease-ring')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Outbreak watch', exact: true })).toBeVisible();
  await expect(page.locator('.atlas-watch .atlas-scope-trigger')).toHaveCount(0);
  await expect(page.locator('.atlas-latest-list > li:not([inert]) .atlas-latest-entry')).toHaveCount(width === 390 ? 7 : 9);
  if (width > 1000) await page.getByRole('button', { name: 'Click to enter full screen' }).click();
  await page.getByRole('tab', { name: 'Reports', exact: true }).click();
  const report = page.locator('.atlas-report').filter({ hasText: 'Rospotrebnadzor called reports of a strict quarantine in Irkutsk Region fake' });
  const next = page.getByRole('button', { name: 'Next report page', exact: true }).first();
  await page.locator('.atlas-report-list').scrollIntoViewIfNeeded();
  while (!await report.count() && await next.isEnabled()) await next.click();
  await expect(report).toHaveCount(1);
  await report.locator(':scope > summary').click();
  await expect(report).toContainText('Rospotrebnadzor called reports of a strict quarantine in Irkutsk Region fake');
  await expect(report.locator('.atlas-original-title')).toContainText('Original title · Russian');
  await report.locator('.atlas-original-title summary').click();
  await expect(report.locator('.atlas-original-title p')).toHaveAttribute('lang', 'ru');
  const quotation = report.locator('.atlas-claim').filter({ has: page.locator('summary') }).first();
  await quotation.locator('summary').click();
  const pair = quotation.locator('.atlas-quotation-pair').first();
  await expect(pair.locator('[lang="ru"]')).toBeVisible();
  await expect(pair.locator('[lang="en"]')).toBeVisible();
  await expect(pair).toContainText('ATLAS draft');
  await expect(pair.locator('blockquote')).toHaveCount(2);
  await page.screenshot({ path: `/tmp/atlas-translation-${width}.png` });
  await page.getByRole('tab', { name: 'Analysis', exact: true }).click();
  await selectAtlasOption(page, 'Analysis view', 'signals');
  await expect(page.getByRole('region', { name: 'Model prediction', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Observation details', exact: true })).toBeVisible();
  await expect(page.locator('summary[aria-label="Analysis view"]')).toContainText('Signals');
  await page.getByRole('region', { name: 'Model prediction', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: `/tmp/atlas-model-observations-${width}.png` });
  await page.getByRole('tab', { name: 'Journeys', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Journeys & connections' })).toBeVisible();
  await expect(page.locator('.atlas-chain-map')).toBeVisible();
  await expect(page.locator('.atlas-chain-tools summary')).toHaveCSS('border-top-width', '0px');
  await expect(page.locator('.atlas-chain-tools summary')).toHaveCSS('min-height', '40px');
  await page.locator('.atlas-chain-tools').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `/tmp/atlas-journeys-selector-${width}.png` });
  await page.getByRole('tab', { name: 'Analysis', exact: true }).click();
  await expect(page.locator('.atlas-analysis')).toHaveAttribute('data-view', 'signals');
  await page.getByRole('tab', { name: 'Trends', exact: true }).click();
  await expect(page.locator('.atlas-chain-section, .atlas-analysis-observations')).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `/tmp/atlas-briefing-${width}.png` });
  expect(errors).toEqual([]);
});
