import { createHash } from 'node:crypto';
import type { AtlasRelease } from '../src/lib/atlas-release';
import { dailyPins, type DailyData } from '../src/lib/atlas-daily';
export const dailyHash = (value: Uint8Array | string) => createHash('sha256').update(value).digest('hex');
export function dailyFixture(release: AtlasRelease, manifestHash = 'c'.repeat(64)): DailyData {
  const date = '2026-10-07T08:00:00Z', quote = 'Enquête en France : 12 cas signalés.';
  const translation = { text: 'Investigation in France: 12 reported cases.', language_tag: 'en' as const, origin: 'atlas_generated' as const, created_at: date, created_by: 'fixture', method_version: 'fixture', review_status: 'unreviewed' as const, reviewed_at: null, reviewed_by: null, review_note: 'Synthetic test translation.' };
  const document = { id: 'daily_doc', channel_id: null, base_document_ids: [], source_id: 'france_spf', source_name: 'Santé publique France', source_role: 'public_health_authority', url: 'https://example.org/daily', content_url: 'https://example.org/daily', title: 'Enquête en France', title_translation: { ...translation, text: 'Investigation in France' }, language_tag: 'fr', publication: '2026-10-07', publication_precision: 'day', modified_at: null, capture: date, source_text_sha256: dailyHash(quote), raw_sha256: dailyHash(quote), parse_status: 'parsed', review_id: 'review_daily', review_state: 'source_checked_draft' as const, reviewed_at: date, reviewed_by: 'fixture', outcome: 'relevant' as const, processing_status: 'weekly_review_pending' as const, finding_ids: ['finding_daily'], country_codes: ['FR'], limitations: ['Synthetic source for interface tests.'] };
  const data: DailyData = { daily_version: '0.2.1', daily_id: 'd'.repeat(64), base_source_export_id: release.export_id, base_manifest_sha256: manifestHash, base_site_sha256: release.assets['atlas-site.json'].sha256, base_map_snapshot_sha256: release.assets['map.json'].sha256, acquisition_sha256: 'e'.repeat(64), annotations_sha256: 'f'.repeat(64), generated_at: date, knowledge_cutoff: date, publication_from: '2026-10-01', publication_until: '2026-10-07', timezone: 'Europe/Amsterdam', selection_policy: 'all_supporting_documents_in_window', software_version: 'fixture', documents: [document, { ...document, id: 'daily_latest', review_id: 'review_latest', finding_ids: [], title: 'Latest daily report', title_translation: null, language_tag: 'en', url: 'https://example.org/latest' }],
    findings: [{ id: 'finding_daily', key: 'count', document_id: 'daily_doc', review_id: 'review_daily', kind: 'reported_count', text: '12 reported cases in France.', status: 'unconfirmed', statement_kind: 'source_statement', attribution: { value: 'Santé publique France', status: 'reported' }, observation_period: { value: '7 October 2026', status: 'reported' }, places: [{ name: 'France', country_code: 'FR', role: 'reporting_scope' }], evidence_ids: ['evidence_daily'], reviewed_at: date, reviewed_by: 'fixture', review_state: 'source_checked_draft' }],
    evidence: [{ id: 'evidence_daily', document_id: 'daily_doc', source_text_sha256: dailyHash(quote), quote_sha256: dailyHash(quote), quote, start: 0, end: [...quote].length, offset_basis: 'unicode_code_points_half_open', language_tag: 'fr', translation }],
    watch_assessments: [], watch_items: [{ attention: 'watch', temporal_status: 'current', development_date: '2026-10-07', date_basis: 'source_report_date', development_finding_keys: ['daily_doc:count'], follow_up_finding_keys: ['daily_doc:count'], counterevidence_finding_keys: [], criteria: [{ kind: 'unusual_event', reason: 'Synthetic event under investigation.', finding_keys: ['daily_doc:count'] }], decision_reason: 'Synthetic event selected for interface testing.', location_label: 'France', diagnostic_label: 'Cause unconfirmed', key_facts: [{ label: 'Cases', text: '12 reported cases in France', finding_keys: ['daily_doc:count'], finding_ids: ['finding_daily'] }], review_due_at: '2026-10-08T08:00:00Z', method_version: 'daily-watch-1.0.1', id: 'watch_daily', key: 'test', finding_keys: ['daily_doc:count'], label: 'Investigation in France', finding_ids: ['finding_daily'], evidence_ids: ['evidence_daily'], document_ids: ['daily_doc'], reason_for_attention: 'The source describes an ongoing investigation.', follow_up_question: 'What will the investigation establish?', reviewed_at: date, reviewed_by: 'fixture', review_state: 'source_checked_draft', scope_kind: 'report_selection', event_identity: 'not_assigned', latest_publication: '2026-10-07', latest_capture: date }],
    source_coverage: [{ source_id: 'france_spf', source_name: 'Santé publique France', source_role: 'public_health_authority', status: 'captured', notes: [], checked_at: date, documents: 2, pending: 2, relevant: 2, reviewed: 2 }], reconciliations: [] };
  data.watch_assessments = structuredClone(data.watch_items);
  return data;
}
export function dailyPointer(data: DailyData) {
  const bytes = Buffer.from(JSON.stringify(data));
  return { version: 1 as const, daily_version: '0.2.1' as const, daily_id: data.daily_id, base_source_export_id: data.base_source_export_id, base_manifest_sha256: data.base_manifest_sha256, published_at: data.generated_at, asset: { sha256: dailyHash(bytes), bytes: bytes.length }, schema_sha256: dailyPins.schema, selector_sha256: dailyPins.selector };
}
