import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

for (const [width,height] of [[390,950],[1280,720],[1280,950],[1512,820]]) test(`One Health network presentation ${width}×${height}`,async({page})=>{
 test.skip(!process.env.ATLAS_HEALTH_PARTIAL,'Requires the partial One Health dataset');
 await page.setViewportSize({width,height});
 await page.emulateMedia({reducedMotion:'reduce',colorScheme:width===390?'dark':'light'});
 await page.goto('/atlas/');
 await page.locator('.atlas-page[data-ready="true"]').waitFor({timeout:60000});
 if(width>=1280){await page.getByRole('button',{name:'Click to enter full screen'}).focus();await page.keyboard.press('Enter');}
 await page.getByRole('tab',{name:'One Health',exact:true}).click();
 const view=page.getByRole('region',{name:'One Health evidence'});
 await view.locator('summary[aria-label="One Health report"]').click();
 await view.getByRole('searchbox').fill('alfalfa sprouted seeds');
 await view.getByRole('option',{name:/alfalfa sprouted seeds/}).first().click();
 await expect(view.getByRole('heading',{name:/Observations/}).locator('svg')).toHaveCount(1);
 await expect(view.locator('.atlas-oh-key')).toHaveCSS('justify-content','center');
 await expect(view.locator('.atlas-oh-lane-title svg')).toHaveCount(3);
 await expect(view.locator('.atlas-oh-node-label')).toHaveCount(6);
 await expect(view.locator('.atlas-oh-node-label').first()).toContainText('Exposure reported');
 expect(await view.locator('.atlas-oh-network > svg').evaluate(el=>{const matrix=(el as SVGSVGElement).getScreenCTM()!;return Math.abs(matrix.a-matrix.d)<0.001;})).toBe(true);
 expect(await view.locator('.atlas-oh-lane-title').evaluateAll(headings=>headings.every(el=>el.scrollWidth<=el.clientWidth+1))).toBe(true);
 await expect(view.locator('.atlas-oh-detail-kind > svg')).toHaveCount(1);
 expect(await view.locator('.atlas-oh-network').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 const node=view.locator('.atlas-oh-node').first();
 await node.locator(':scope > g').click();
 await expect(node).toHaveAttribute('aria-pressed','true');
 await expect(node).toHaveCSS('outline-style','none');
 await expect(node.locator(':scope > g > :first-child')).not.toHaveCSS('filter','none');
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 await expect(view.getByRole('complementary')).toContainText('Source evidence');
 const lastNode=view.locator('.atlas-oh-node').last();
 const lastId=await lastNode.getAttribute('data-entry-id');
 const nodeEntries=view.locator('.atlas-oh-node-entries');
 await nodeEntries.evaluate(el=>{el.scrollTop=0;});
 await lastNode.hover();
 const matchingNode=nodeEntries.locator(`[data-entry-id="${lastId}"]`);
 await expect(matchingNode).toHaveAttribute('data-highlighted','true');
 expect(await nodeEntries.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 expect(await matchingNode.evaluate(el=>{
   const entry=el.getBoundingClientRect(),frame=el.closest('.atlas-oh-node-entries')!.getBoundingClientRect();
   return Math.min(entry.bottom,frame.bottom)-Math.max(entry.top,frame.top)>=Math.min(entry.height,frame.height)-1;
 })).toBe(true);
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 const firstEntry=nodeEntries.locator('.atlas-oh-entry').first();
 await firstEntry.hover();
 await expect(node).toHaveAttribute('data-highlighted','true');
 await node.focus();
 await page.keyboard.press('Enter');
 await expect(firstEntry).toHaveAttribute('aria-pressed','true');
 const edge=view.locator('.atlas-oh-edge').first();
 await view.locator('.atlas-oh-network').scrollIntoViewIfNeeded();
 const edgePoint=await edge.locator('.atlas-oh-edge-line').evaluate(el=>{
   const path=el as SVGPathElement,p=path.getPointAtLength(path.getTotalLength()/2);
   const point=new DOMPoint(p.x,p.y).matrixTransform(path.getScreenCTM()!);
   return {x:point.x,y:point.y};
 });
 await page.mouse.move(edgePoint.x,edgePoint.y);
 const matchingEdge=view.locator('.atlas-oh-relations .atlas-oh-entry').first();
 await expect(matchingEdge).toHaveAttribute('data-highlighted','true');
 await matchingEdge.hover();
 await expect(edge).toHaveAttribute('data-highlighted','true');
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 await expect(view.locator('.atlas-oh-figure h3')).toContainText('6 nodes · 2 connections');
 await expect(view.locator('.atlas-oh-observations summary')).toHaveCount(0);
 await expect(view.locator('.atlas-oh-entry-panels h4')).toHaveCount(0);
 await expect(view.getByRole('heading',{name:'Observation list',exact:true})).toBeVisible();
 await expect(view.locator('.atlas-oh-entry-panels > section').last()).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 const list=view.getByRole('list',{name:'One Health observations'}).first();
 const observation=list.getByRole('button').first();
 await expect(observation).toContainText('Exposure reported');
 await expect(observation).toContainText('Interviewed cases');
 await expect(observation.locator('.atlas-oh-list-marker text')).toHaveText('1');
 await observation.focus();
 await page.keyboard.press('Enter');
 await expect(observation).toHaveAttribute('aria-pressed','true');
 await expect(view.locator('.atlas-oh-node').first()).toHaveAttribute('data-selected','true');
 const panels=view.locator('.atlas-oh-entry-panels > section');
 const heights=await panels.evaluateAll(items=>items.map(el=>el.getBoundingClientRect().height));
 expect(Math.abs(heights[0]-heights[1])).toBeLessThan(1);
 const connection=view.getByRole('group',{name:'One Health relationships'}).getByRole('button').first();
 await connection.click();
 await expect(connection).toHaveAttribute('aria-pressed','true');
 await expect(view.locator('.atlas-oh-edge').first()).toHaveAttribute('data-selected','true');
 await expect(view.locator('.atlas-oh-edge').first()).toHaveAttribute('aria-pressed','true');
 await expect(view.locator('.atlas-oh-edge').first()).toHaveCSS('outline-style','none');
 await expect(view.locator('.atlas-oh-edge').first().locator('.atlas-oh-edge-line')).not.toHaveCSS('filter','none');
 await expect(connection).toHaveCSS('border-left-width','0px');
 const nodeTitle=await observation.locator('strong').boundingBox();
 const edgeTitle=await connection.locator('strong').boundingBox();
 expect(Math.abs(nodeTitle!.x-edgeTitle!.x)).toBeLessThan(1);
 await expect(connection.locator('.atlas-oh-list-finding')).toContainText('Exposure');
 await expect(connection.locator('.atlas-oh-connection-marker > span')).toHaveText('2 — 1');
 await expect(connection.locator('.atlas-oh-connection-marker circle')).toHaveCount(2);
 if(width>=1280){
   const main=view.locator('.atlas-oh-main');
   await expect(main).toHaveCSS('overflow-y','hidden');
   expect(await main.evaluate(el=>el.scrollHeight<=el.clientHeight+1)).toBe(true);
   const figure=view.locator('.atlas-oh-figure');
   const figureBounds=await figure.boundingBox();
   const listBounds=await view.locator('.atlas-oh-observations').boundingBox();
   const mainBounds=await main.boundingBox();
   expect(listBounds!.y+listBounds!.height).toBeLessThanOrEqual(mainBounds!.y+mainBounds!.height+1);
   await nodeEntries.evaluate(el=>{el.scrollTop=0;});
   await nodeEntries.hover();
   await page.mouse.wheel(0,300);
   await expect.poll(()=>nodeEntries.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
   expect(await figure.boundingBox()).toEqual(figureBounds);
   expect(await main.evaluate(el=>el.scrollTop)).toBe(0);
   await main.screenshot({path:`/tmp/atlas-health-column-${width}-${height}.png`});
 }

 await view.locator('.atlas-oh-observations').screenshot({path:`/tmp/atlas-health-entry-panels-${width}-${height}.png`});
 expect(await list.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await list.screenshot({path:`/tmp/atlas-health-observations-${width}-${height}.png`});
 expect((await new AxeBuilder({page}).include('.atlas-one-health').analyze()).violations).toEqual([]);
 await view.locator('.atlas-oh-detail').screenshot({path:`/tmp/atlas-health-details-${width}-${height}.png`});
 await view.locator('.atlas-oh-figure').screenshot({path:`/tmp/atlas-network-refined-${width}-${height}.png`});
});
