import { bundle as fixture } from './atlas-fixture';
import type { AtlasSiteBundle, AtlasOneHealthNode, AtlasOneHealthTiming, AtlasOneHealthSamplingAssessment, AtlasOneHealthContext, AtlasObservationTime, AtlasValue } from '../src/lib/atlas-contract';

export function healthPanelsFixture():AtlasSiteBundle {
 const base=structuredClone(fixture);
 const measure=base.metrics.measures[0], record=base.records.find(r=>r.id===measure.source_reference.record_id)!;
 const other=base.records.find(r=>r.document_id!==record.document_id)!;
 const missing:AtlasValue={value:null,status:'not_reported'};
 const value=(value:string):AtlasValue=>({value,status:'reported'});
 const assertion={...base.assertions.find(a=>a.record_id===record.id)!,id:'test-oh-assertion',text:'Synthetic One Health panel fixture; not a source finding.'};
 const evidence={...base.evidence.find(e=>e.record_id===record.id)!,id:'test-oh-evidence',quote:'Synthetic dates and sample counts for interface testing only.'};
 const support={record_ids:[record.id],document_ids:[record.document_id],assertion_ids:[assertion.id],evidence_ids:[evidence.id],eligibility:{rule:'all_supporting_records_in_window' as const,record_ids:[record.id],partial:'hide_relationship_keep_visible_assertions' as const}};
 const node:AtlasOneHealthNode={...support,id:'test-oh-human',key:'human',record_id:record.id,label:'Synthetic sampled population',domain:'human',entity_kind:'population',roles:['sampled_matrix'],scope:'episode',taxon:value('Humans'),material:missing,agent:value('Synthetic organism'),agent_kind:'pathogen',finding:'agent_detected',sampling:{sample_unit:value('specimens'),frame:value('Synthetic sampling group'),collection_method:missing,test_method:missing},place_ids:[],location_note:'No reviewed location in this fixture.',uncertainty:'Synthetic fixture',topic_ids:[record.topic_id],measure_ids:[],observation_date:missing,period_start:missing,period_end:missing,date_basis:'unknown',period_label:missing,date_note:'Individual source dates are in the timing records.'};
 const time=(start:string|null,precision:AtlasObservationTime['precision'],kind:AtlasObservationTime['kind']='sample_collection'):AtlasObservationTime=>({kind,extent:start?'point':'unknown',start:start?value(start):missing,end:missing,precision,certainty:'exact',label:'Synthetic collection date',reason:'Source precision is retained in this interface fixture.'});
 const review={...support,record_id:record.id,reason:'Synthetic review for display tests.',reviewed_at:'2026-09-28T00:00:00Z',reviewed_by:'Synthetic fixture',source_assertion_id:assertion.id,review_state:'source_checked_draft' as const};
 const timing=(id:string,t:AtlasObservationTime):AtlasOneHealthTiming=>({...review,id,key:id,node_id:node.id,time:t});
 const positive={...measure,measure_id:'test-positive',value:0,unit:'samples',metric:'positive_samples',label:'Synthetic positive specimens',denominator:10};
 const tested={...measure,measure_id:'test-tested',value:10,unit:'samples',metric:'samples_tested',label:'Synthetic tested specimens',denominator:null};
 const sampling:AtlasOneHealthSamplingAssessment={...review,id:'test-sampling',key:'sampling',node_id:node.id,time:time('2026-06','month'),positive_measure_id:positive.measure_id,tested_measure_id:tested.measure_id,pair_status:'matched',unit:value('specimens'),frame:value('Synthetic sampling group'),population:value('Synthetic sampled population'),target:value('Synthetic organism'),method:missing,pooling:missing,clustering:missing,repeated_sampling:missing,display:'proportion',proportion:0,display_reason:'Descriptive fraction among the matched sampled units, not population prevalence.'};
 const context:AtlasOneHealthContext={...review,id:'test-context',key:'context',label:'Synthetic water protection action',kind:'reported_intervention',time:time('2026-07','month','intervention'),variable:missing,method:missing,place_ids:[],linkage_note:'Source-described action linked to the sampled population.',node_ids:[node.id],measure_ids:[]};
 const independent:AtlasOneHealthContext={...context,id:'test-independent',key:'independent',record_id:other.id,record_ids:[other.id],document_ids:[other.document_id],assertion_ids:[base.assertions.find(a=>a.record_id===other.id)!.id],source_assertion_id:base.assertions.find(a=>a.record_id===other.id)!.id,evidence_ids:[base.evidence.find(e=>e.record_id===other.id)!.id],eligibility:{...support.eligibility,record_ids:[other.id]},label:'Synthetic independent context',node_ids:[],kind:'reported_condition',linkage_note:'No association with a network observation is asserted.'};
 return {...base,contract_version:'1.8.0',metrics:{...base.metrics,contract_version:'0.4.0',reviewed_series:[],measures:[...base.metrics.measures,positive,tested]},reviewed_chains:[],diseases:[],disease_reviews:[],one_health_reviews:[],one_health_nodes:[node],one_health_relations:[],one_health_timings:[timing('test-day',time('2026-06-15','day','onset')),timing('test-month',time('2026-07','month')),timing('test-year',{...time('2026','year','exposure'),certainty:'approximately'}),timing('test-undated',{...time(null,'day'),extent:'open_interval',end:value('2026-06-30')}),timing('test-open',{...time('2022','year','detection'),extent:'open_interval'}),timing('test-unknown-kind',time('2026-07','month','unknown')),timing('test-cutoff',time('2026-08-31','day','reporting_cutoff'))],one_health_sampling_assessments:[sampling,{...sampling,id:'test-unresolved',key:'unresolved',pair_status:'unresolved',display:'counts_only',proportion:null,display_reason:'Sample pairing has not been established.',time:time(null,'unknown')}],one_health_contexts:[context,independent,{...context,id:'test-undated-context',key:'undated-context',label:'Synthetic condition with unresolved date kind',kind:'reported_condition',time:time('2026-07','month','unknown')}],assertions:[...base.assertions,assertion,...[positive,tested].map(m=>({...assertion,id:`assertion:${m.measure_id}`,measure_id:m.measure_id,text:m.label}))],evidence:[...base.evidence,evidence]};
}
