// Types follow the ATLAS daily export schema.
export type DailyCoverage = { checked_at: string | null; documents: number; notes: (string)[]; pending: number; relevant: number; reviewed: number; source_id: string; source_name: string; source_role: string; status: string };
export type DailyDocument = { base_document_ids: (string)[]; capture: string; channel_id: string | null; content_url: string; country_codes: (string)[]; finding_ids: (string)[]; id: string; language_tag: string; limitations: (string)[]; modified_at: string | null; outcome: "pending" | "relevant" | "no_relevant_content" | "needs_review"; parse_status: string; processing_status: "weekly_review_pending" | "weekly_reviewed"; publication: string | null; publication_precision: string; raw_sha256: string; review_id: string | null; review_state: "not_reviewed" | "source_checked_draft"; reviewed_at: string | null; reviewed_by: string | null; source_id: string; source_name: string; source_role: string; source_text_sha256: string; title: string; title_translation: Translation | null; url: string };
export type DailyEvidence = { document_id: string; end: number; id: string; language_tag: string; offset_basis: "unicode_code_points_half_open"; quote: string; quote_sha256: string; source_text_sha256: string; start: number; translation: Translation | null };
export type DailyFinding = { attribution: TextValue; document_id: string; evidence_ids: (string)[]; id: string; key: string; kind: "suspected_disease" | "diagnostic_status" | "reported_count" | "geographic_extent" | "spatial_link" | "response_measure" | "potential_source" | "development"; observation_period: TextValue; places: (PlaceInput)[]; review_id: string; review_state: "source_checked_draft"; reviewed_at: string; reviewed_by: string; statement_kind: "source_statement" | "attributed_hypothesis" | "analyst_hypothesis"; status: "reported" | "source_suspected" | "source_probable" | "source_confirmed" | "source_ruled_out" | "unconfirmed" | "disputed" | "unresolved"; text: string };
export type DailyWatch = { attention: "urgent" | "heightened" | "watch" | "not_selected"; counterevidence_finding_keys: (string)[]; criteria: (WatchCriterion)[]; date_basis: "source_event_date" | "source_report_date" | "unknown"; decision_reason: string; development_date: string | null; development_finding_keys: (string)[]; diagnostic_label: string; document_ids: (string)[]; event_identity: "not_assigned"; evidence_ids: (string)[]; finding_ids: (string)[]; finding_keys: (string)[]; follow_up_finding_keys: (string)[]; follow_up_question: string; id: string; key: string; key_facts: (DailyWatchFact)[]; label: string; latest_capture: string; latest_publication: string | null; location_label: string; method_version: "daily-watch-1.0.0"; reason_for_attention: string; review_due_at: string; review_state: "source_checked_draft"; reviewed_at: string; reviewed_by: string; scope_kind: "report_selection"; temporal_status: "current" | "routine" | "retrospective" | "unknown" | "resolved" };
export type DailyWatchFact = { finding_ids: (string)[]; finding_keys: (string)[]; label: string; text: string };
export type PlaceInput = { country_code: string | null; name: string; role: "reporting_scope" | "occurrence" | "exposure" | "travel_origin" | "travel_destination" | "context" };
export type Reconciliation = { disposition: "integrated" | "reviewed_not_exported" | "pending"; reason: string; record_ids: (string)[]; review_id: string; reviewed_at: string; reviewed_by: string; weekly_export_id: string; weekly_inbox_sha256: string };
export type Status = "reported" | "not_reported" | "unknown" | "not_applicable" | "pending_verification" | "conflicting" | "not_extracted" | "not_comparable" | "access_restricted";
export type TextValue = { status?: Status; value?: string | null };
export type Translation = { created_at: string; created_by: string; language_tag?: "en"; method_version: string; origin: "atlas_generated" | "publisher_provided"; pairing_evidence_ids?: (string)[]; publisher_text_id?: string | null; review_note: string; review_status: "unreviewed" | "source_checked" | "human_approved"; reviewed_at: string | null; reviewed_by: string | null; text: string };
export type WatchCriterion = { finding_keys: (string)[]; kind: "severe_impact" | "spread_change" | "unusual_event" | "response_gap" | "time_sensitive_action"; reason: string };
export type DailyData = { acquisition_sha256: string; annotations_sha256: string; base_manifest_sha256: string; base_map_snapshot_sha256: string; base_site_sha256: string; base_source_export_id: string; daily_id: string; daily_version: "0.2.0"; documents: (DailyDocument)[]; evidence: (DailyEvidence)[]; findings: (DailyFinding)[]; generated_at: string; knowledge_cutoff: string; publication_from: string; publication_until: string; reconciliations: (Reconciliation)[]; selection_policy: "all_supporting_documents_in_window"; software_version: string; source_coverage: (DailyCoverage)[]; timezone: "Europe/Amsterdam"; watch_assessments: (DailyWatch)[]; watch_items: (DailyWatch)[] };
